11-13 11:10:27 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "MATRICULA" not found; SQL statement:
INSERT INTO professor (matricula,nome,sobrenome,titulo,email,usuario,senha) VALUES (?,?,?,?,?,?,?) [42122-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:595)
	at org.h2.command.Parser.parseColumn(Parser.java:793)
	at org.h2.command.Parser.parseColumnList(Parser.java:778)
	at org.h2.command.Parser.parseInsert(Parser.java:958)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1119)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:71)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1049)
	at clojure.java.jdbc.internal$prepare_statement_STAR_$fn__162.invoke(internal.clj:314)
	at clojure.java.jdbc.internal$prepare_statement_STAR_.doInvoke(internal.clj:313)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at clojure.java.jdbc.internal$do_prepared_return_keys_STAR_.invoke(internal.clj:337)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:603)
	at clojure.java.jdbc$insert_values.doInvoke(jdbc.clj:263)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at clojure.java.jdbc$insert_records$ins_v__216.invoke(jdbc.clj:278)
	at clojure.core$map$fn__4087.invoke(core.clj:2434)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.RT.seq(RT.java:473)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$dorun.invoke(core.clj:2725)
	at clojure.core$doall.invoke(core.clj:2741)
	at clojure.java.jdbc$insert_records.doInvoke(jdbc.clj:279)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at dominio.BD.insercao$inserir_professor$fn__228.invoke(insercao.clj:26)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.insercao$inserir_professor.invoke(insercao.clj:25)
	at dominio.dominiox$eval364.invoke(NO_SOURCE_FILE:12)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-13 11:10:27 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "MATRICULA" not found; SQL statement:
INSERT INTO professor (matricula,nome,sobrenome,titulo,email,usuario,senha) VALUES (?,?,?,?,?,?,?) [42122-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:595)
	at org.h2.command.Parser.parseColumn(Parser.java:793)
	at org.h2.command.Parser.parseColumnList(Parser.java:778)
	at org.h2.command.Parser.parseInsert(Parser.java:958)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1119)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:71)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1049)
	at clojure.java.jdbc.internal$prepare_statement_STAR_$fn__162.invoke(internal.clj:314)
	at clojure.java.jdbc.internal$prepare_statement_STAR_.doInvoke(internal.clj:313)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at clojure.java.jdbc.internal$do_prepared_return_keys_STAR_.invoke(internal.clj:337)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:603)
	at clojure.java.jdbc$insert_values.doInvoke(jdbc.clj:263)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at clojure.java.jdbc$insert_records$ins_v__216.invoke(jdbc.clj:278)
	at clojure.core$map$fn__4087.invoke(core.clj:2434)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.RT.seq(RT.java:473)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$dorun.invoke(core.clj:2725)
	at clojure.core$doall.invoke(core.clj:2741)
	at clojure.java.jdbc$insert_records.doInvoke(jdbc.clj:279)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at dominio.BD.insercao$inserir_professor$fn__228.invoke(insercao.clj:26)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.insercao$inserir_professor.invoke(insercao.clj:25)
	at dominio.dominiox$eval364.invoke(NO_SOURCE_FILE:12)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-13 11:10:27 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "MATRICULA" not found; SQL statement:
INSERT INTO professor (matricula,nome,sobrenome,titulo,email,usuario,senha) VALUES (?,?,?,?,?,?,?) [42122-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:595)
	at org.h2.command.Parser.parseColumn(Parser.java:793)
	at org.h2.command.Parser.parseColumnList(Parser.java:778)
	at org.h2.command.Parser.parseInsert(Parser.java:958)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1119)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:71)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at clojure.java.jdbc.internal$prepare_statement_STAR_$fn__162.invoke(internal.clj:317)
	at clojure.java.jdbc.internal$prepare_statement_STAR_.doInvoke(internal.clj:313)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at clojure.java.jdbc.internal$do_prepared_return_keys_STAR_.invoke(internal.clj:337)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:603)
	at clojure.java.jdbc$insert_values.doInvoke(jdbc.clj:263)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at clojure.java.jdbc$insert_records$ins_v__216.invoke(jdbc.clj:278)
	at clojure.core$map$fn__4087.invoke(core.clj:2434)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.RT.seq(RT.java:473)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$dorun.invoke(core.clj:2725)
	at clojure.core$doall.invoke(core.clj:2741)
	at clojure.java.jdbc$insert_records.doInvoke(jdbc.clj:279)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at dominio.BD.insercao$inserir_professor$fn__228.invoke(insercao.clj:26)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.insercao$inserir_professor.invoke(insercao.clj:25)
	at dominio.dominiox$eval364.invoke(NO_SOURCE_FILE:12)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-13 11:13:07 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "NUMERO" not found; SQL statement:
CREATE TABLE professor (matricula VARCHAR(20) NOT NULL, nome VARCHAR(50) NOT NULL, sobrenome VARCHAR(100) NOT NULL, titulo VARCHAR(20) NOT NULL, email VARCHAR(50) NOT NULL, usuario VARCHAR(30) NOT NULL, senha VARCHAR(30) NOT NULL, CONSTRAINT PK_PROFESSOR PRIMARY KEY(numero)) [42122-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:595)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:75)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:97)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:168)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:633)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:713)
	at dominio.BD.persistence$criar_tabela_professor$fn__78.invoke(persistence.clj:22)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_professor.invoke(persistence.clj:21)
	at dominio.dominiox$eval346.invoke(NO_SOURCE_FILE:2)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-13 11:13:07 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Column "NUMERO" not found; SQL statement:
CREATE TABLE professor (matricula VARCHAR(20) NOT NULL, nome VARCHAR(50) NOT NULL, sobrenome VARCHAR(100) NOT NULL, titulo VARCHAR(20) NOT NULL, email VARCHAR(50) NOT NULL, usuario VARCHAR(30) NOT NULL, senha VARCHAR(30) NOT NULL, CONSTRAINT PK_PROFESSOR PRIMARY KEY(numero)) [42122-160]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:648)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:713)
	at dominio.BD.persistence$criar_tabela_professor$fn__78.invoke(persistence.clj:22)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_professor.invoke(persistence.clj:21)
	at dominio.dominiox$eval346.invoke(NO_SOURCE_FILE:2)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
org.h2.jdbc.JdbcSQLException: Column "NUMERO" not found; SQL statement:
CREATE TABLE professor (matricula VARCHAR(20) NOT NULL, nome VARCHAR(50) NOT NULL, sobrenome VARCHAR(100) NOT NULL, titulo VARCHAR(20) NOT NULL, email VARCHAR(50) NOT NULL, usuario VARCHAR(30) NOT NULL, senha VARCHAR(30) NOT NULL, CONSTRAINT PK_PROFESSOR PRIMARY KEY(numero)) [42122-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:595)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:75)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:97)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:168)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:633)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:713)
	at dominio.BD.persistence$criar_tabela_professor$fn__78.invoke(persistence.clj:22)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_professor.invoke(persistence.clj:21)
	at dominio.dominiox$eval346.invoke(NO_SOURCE_FILE:2)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-13 11:16:54 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "HIERARQUIA" not found; SQL statement:
INSERT INTO disciplina (sigla,nome,hierarquia) VALUES (?,?,?) [42122-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:595)
	at org.h2.command.Parser.parseColumn(Parser.java:793)
	at org.h2.command.Parser.parseColumnList(Parser.java:778)
	at org.h2.command.Parser.parseInsert(Parser.java:958)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1119)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:71)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1049)
	at clojure.java.jdbc.internal$prepare_statement_STAR_$fn__162.invoke(internal.clj:314)
	at clojure.java.jdbc.internal$prepare_statement_STAR_.doInvoke(internal.clj:313)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at clojure.java.jdbc.internal$do_prepared_return_keys_STAR_.invoke(internal.clj:337)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:603)
	at clojure.java.jdbc$insert_values.doInvoke(jdbc.clj:263)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at clojure.java.jdbc$insert_records$ins_v__216.invoke(jdbc.clj:278)
	at clojure.core$map$fn__4087.invoke(core.clj:2434)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.RT.seq(RT.java:473)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$dorun.invoke(core.clj:2725)
	at clojure.core$doall.invoke(core.clj:2741)
	at clojure.java.jdbc$insert_records.doInvoke(jdbc.clj:279)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at dominio.BD.insercao$inserir_disciplina$fn__231.invoke(insercao.clj:35)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.insercao$inserir_disciplina.invoke(insercao.clj:33)
	at dominio.dominiox$eval350.invoke(NO_SOURCE_FILE:5)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-13 11:16:54 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "HIERARQUIA" not found; SQL statement:
INSERT INTO disciplina (sigla,nome,hierarquia) VALUES (?,?,?) [42122-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:595)
	at org.h2.command.Parser.parseColumn(Parser.java:793)
	at org.h2.command.Parser.parseColumnList(Parser.java:778)
	at org.h2.command.Parser.parseInsert(Parser.java:958)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1119)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:71)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1049)
	at clojure.java.jdbc.internal$prepare_statement_STAR_$fn__162.invoke(internal.clj:314)
	at clojure.java.jdbc.internal$prepare_statement_STAR_.doInvoke(internal.clj:313)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at clojure.java.jdbc.internal$do_prepared_return_keys_STAR_.invoke(internal.clj:337)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:603)
	at clojure.java.jdbc$insert_values.doInvoke(jdbc.clj:263)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at clojure.java.jdbc$insert_records$ins_v__216.invoke(jdbc.clj:278)
	at clojure.core$map$fn__4087.invoke(core.clj:2434)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.RT.seq(RT.java:473)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$dorun.invoke(core.clj:2725)
	at clojure.core$doall.invoke(core.clj:2741)
	at clojure.java.jdbc$insert_records.doInvoke(jdbc.clj:279)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at dominio.BD.insercao$inserir_disciplina$fn__231.invoke(insercao.clj:35)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.insercao$inserir_disciplina.invoke(insercao.clj:33)
	at dominio.dominiox$eval350.invoke(NO_SOURCE_FILE:5)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-13 11:16:54 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "HIERARQUIA" not found; SQL statement:
INSERT INTO disciplina (sigla,nome,hierarquia) VALUES (?,?,?) [42122-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:595)
	at org.h2.command.Parser.parseColumn(Parser.java:793)
	at org.h2.command.Parser.parseColumnList(Parser.java:778)
	at org.h2.command.Parser.parseInsert(Parser.java:958)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1119)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:71)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at clojure.java.jdbc.internal$prepare_statement_STAR_$fn__162.invoke(internal.clj:317)
	at clojure.java.jdbc.internal$prepare_statement_STAR_.doInvoke(internal.clj:313)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at clojure.java.jdbc.internal$do_prepared_return_keys_STAR_.invoke(internal.clj:337)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:603)
	at clojure.java.jdbc$insert_values.doInvoke(jdbc.clj:263)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at clojure.java.jdbc$insert_records$ins_v__216.invoke(jdbc.clj:278)
	at clojure.core$map$fn__4087.invoke(core.clj:2434)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.RT.seq(RT.java:473)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$dorun.invoke(core.clj:2725)
	at clojure.core$doall.invoke(core.clj:2741)
	at clojure.java.jdbc$insert_records.doInvoke(jdbc.clj:279)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at dominio.BD.insercao$inserir_disciplina$fn__231.invoke(insercao.clj:35)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.insercao$inserir_disciplina.invoke(insercao.clj:33)
	at dominio.dominiox$eval350.invoke(NO_SOURCE_FILE:5)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-13 11:20:55 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "APRESENTACAO" not found; SQL statement:
INSERT INTO apresentacao (idAp,conteudo,tipo,estUtilizacao,xmlApresentacao) VALUES (?,?,?,?,?) [42102-160]
11-13 11:20:55 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "APRESENTACAO" not found; SQL statement:
INSERT INTO apresentacao (idAp,conteudo,tipo,estUtilizacao,xmlApresentacao) VALUES (?,?,?,?,?) [42102-160]
11-13 11:20:55 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "APRESENTACAO" not found; SQL statement:
INSERT INTO apresentacao (idAp,conteudo,tipo,estUtilizacao,xmlApresentacao) VALUES (?,?,?,?,?) [42102-160]
11-13 11:21:14 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "ESTUTILIZACAO" not found; SQL statement:
INSERT INTO apresentacao (idAp,conteudo,tipo,estUtilizacao,xmlApresentacao) VALUES (?,?,?,?,?) [42122-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:595)
	at org.h2.command.Parser.parseColumn(Parser.java:793)
	at org.h2.command.Parser.parseColumnList(Parser.java:778)
	at org.h2.command.Parser.parseInsert(Parser.java:958)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1119)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:71)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1049)
	at clojure.java.jdbc.internal$prepare_statement_STAR_$fn__162.invoke(internal.clj:314)
	at clojure.java.jdbc.internal$prepare_statement_STAR_.doInvoke(internal.clj:313)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at clojure.java.jdbc.internal$do_prepared_return_keys_STAR_.invoke(internal.clj:337)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:603)
	at clojure.java.jdbc$insert_values.doInvoke(jdbc.clj:263)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at clojure.java.jdbc$insert_records$ins_v__216.invoke(jdbc.clj:278)
	at clojure.core$map$fn__4087.invoke(core.clj:2434)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.RT.seq(RT.java:473)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$dorun.invoke(core.clj:2725)
	at clojure.core$doall.invoke(core.clj:2741)
	at clojure.java.jdbc$insert_records.doInvoke(jdbc.clj:279)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at dominio.BD.insercao$inserir_apresentacao$fn__243.invoke(insercao.clj:77)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.insercao$inserir_apresentacao.invoke(insercao.clj:71)
	at dominio.dominiox$eval356.invoke(NO_SOURCE_FILE:8)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-13 11:21:14 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "ESTUTILIZACAO" not found; SQL statement:
INSERT INTO apresentacao (idAp,conteudo,tipo,estUtilizacao,xmlApresentacao) VALUES (?,?,?,?,?) [42122-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:595)
	at org.h2.command.Parser.parseColumn(Parser.java:793)
	at org.h2.command.Parser.parseColumnList(Parser.java:778)
	at org.h2.command.Parser.parseInsert(Parser.java:958)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1119)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:71)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1049)
	at clojure.java.jdbc.internal$prepare_statement_STAR_$fn__162.invoke(internal.clj:314)
	at clojure.java.jdbc.internal$prepare_statement_STAR_.doInvoke(internal.clj:313)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at clojure.java.jdbc.internal$do_prepared_return_keys_STAR_.invoke(internal.clj:337)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:603)
	at clojure.java.jdbc$insert_values.doInvoke(jdbc.clj:263)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at clojure.java.jdbc$insert_records$ins_v__216.invoke(jdbc.clj:278)
	at clojure.core$map$fn__4087.invoke(core.clj:2434)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.RT.seq(RT.java:473)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$dorun.invoke(core.clj:2725)
	at clojure.core$doall.invoke(core.clj:2741)
	at clojure.java.jdbc$insert_records.doInvoke(jdbc.clj:279)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at dominio.BD.insercao$inserir_apresentacao$fn__243.invoke(insercao.clj:77)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.insercao$inserir_apresentacao.invoke(insercao.clj:71)
	at dominio.dominiox$eval356.invoke(NO_SOURCE_FILE:8)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-13 11:21:14 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "ESTUTILIZACAO" not found; SQL statement:
INSERT INTO apresentacao (idAp,conteudo,tipo,estUtilizacao,xmlApresentacao) VALUES (?,?,?,?,?) [42122-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:595)
	at org.h2.command.Parser.parseColumn(Parser.java:793)
	at org.h2.command.Parser.parseColumnList(Parser.java:778)
	at org.h2.command.Parser.parseInsert(Parser.java:958)
	at org.h2.command.Parser.parsePrepared(Parser.java:375)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1119)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:71)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at clojure.java.jdbc.internal$prepare_statement_STAR_$fn__162.invoke(internal.clj:317)
	at clojure.java.jdbc.internal$prepare_statement_STAR_.doInvoke(internal.clj:313)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at clojure.java.jdbc.internal$do_prepared_return_keys_STAR_.invoke(internal.clj:337)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:603)
	at clojure.java.jdbc$insert_values.doInvoke(jdbc.clj:263)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at clojure.java.jdbc$insert_records$ins_v__216.invoke(jdbc.clj:278)
	at clojure.core$map$fn__4087.invoke(core.clj:2434)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.RT.seq(RT.java:473)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$dorun.invoke(core.clj:2725)
	at clojure.core$doall.invoke(core.clj:2741)
	at clojure.java.jdbc$insert_records.doInvoke(jdbc.clj:279)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at dominio.BD.insercao$inserir_apresentacao$fn__243.invoke(insercao.clj:77)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.insercao$inserir_apresentacao.invoke(insercao.clj:71)
	at dominio.dominiox$eval356.invoke(NO_SOURCE_FILE:8)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-13 11:22:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ESTILOESTUDANTE" already exists; SQL statement:
CREATE TABLE estiloEstudante (matricula VARCHAR(20) NOT NULL, sigla VARCHAR(20) NOT NULL, selecao VARCHAR(20) NOT NULL, organizacao VARCHAR(20) NOT NULL, utilizacao VARCHAR(20) NOT NULL, CONSTRAINT PK_ESTEST PRIMARY KEY(matricula, sigla), CONSTRAINT FK_ESTEST_DISC FOREIGN KEY(sigla)
             REFERENCES disciplina(sigla), CONSTRAINT FK_ESTEST_ALU FOREIGN KEY(matricula)
             REFERENCES aluno(matricula)) [42101-160]
11-13 11:22:45 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Table "ESTILOESTUDANTE" already exists; SQL statement:
CREATE TABLE estiloEstudante (matricula VARCHAR(20) NOT NULL, sigla VARCHAR(20) NOT NULL, selecao VARCHAR(20) NOT NULL, organizacao VARCHAR(20) NOT NULL, utilizacao VARCHAR(20) NOT NULL, CONSTRAINT PK_ESTEST PRIMARY KEY(matricula, sigla), CONSTRAINT FK_ESTEST_DISC FOREIGN KEY(sigla)
             REFERENCES disciplina(sigla), CONSTRAINT FK_ESTEST_ALU FOREIGN KEY(matricula)
             REFERENCES aluno(matricula)) [42101-160]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:648)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:713)
	at dominio.BD.persistence$criar_tabela_estiloEstudante$fn__96.invoke(persistence.clj:98)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_estiloEstudante.invoke(persistence.clj:97)
	at dominio.dominiox$eval344.invoke(NO_SOURCE_FILE:2)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
org.h2.jdbc.JdbcSQLException: Table "ESTILOESTUDANTE" already exists; SQL statement:
CREATE TABLE estiloEstudante (matricula VARCHAR(20) NOT NULL, sigla VARCHAR(20) NOT NULL, selecao VARCHAR(20) NOT NULL, organizacao VARCHAR(20) NOT NULL, utilizacao VARCHAR(20) NOT NULL, CONSTRAINT PK_ESTEST PRIMARY KEY(matricula, sigla), CONSTRAINT FK_ESTEST_DISC FOREIGN KEY(sigla)
             REFERENCES disciplina(sigla), CONSTRAINT FK_ESTEST_ALU FOREIGN KEY(matricula)
             REFERENCES aluno(matricula)) [42101-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:108)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:633)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:713)
	at dominio.BD.persistence$criar_tabela_estiloEstudante$fn__96.invoke(persistence.clj:98)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_estiloEstudante.invoke(persistence.clj:97)
	at dominio.dominiox$eval344.invoke(NO_SOURCE_FILE:2)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-13 12:46:00 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "APRESENTACAO" not found; SQL statement:
CREATE TABLE estiloEstudante (matricula VARCHAR(20) NOT NULL, sigla VARCHAR(20) NOT NULL, selecao VARCHAR(20) NOT NULL, organizacao VARCHAR(20) NOT NULL, utilizacao VARCHAR(20) NOT NULL, CONSTRAINT PK_ESTEST PRIMARY KEY(matricula, sigla), CONSTRAINT FK_ESTEST_DISC FOREIGN KEY(sigla)
             REFERENCES disciplina(sigla), CONSTRAINT FK_ESTEST_ALU FOREIGN KEY(matricula)
             REFERENCES aluno(matricula), CONSTRAINT FK_ESTEST_APRE1 FOREIGN KEY(utilizacao)
             REFERENCES apresentacao(utilizacao), CONSTRAINT FK_ESTEST_APRE2 FOREIGN KEY(selecao)
             REFERENCES apresentacao(selecao), CONSTRAINT FK_ESTEST_APRE3 FOREIGN KEY(organizacao)
             REFERENCES apresentacao(organizacao)) [42102-160]
11-13 12:46:00 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Table "APRESENTACAO" not found; SQL statement:
CREATE TABLE estiloEstudante (matricula VARCHAR(20) NOT NULL, sigla VARCHAR(20) NOT NULL, selecao VARCHAR(20) NOT NULL, organizacao VARCHAR(20) NOT NULL, utilizacao VARCHAR(20) NOT NULL, CONSTRAINT PK_ESTEST PRIMARY KEY(matricula, sigla), CONSTRAINT FK_ESTEST_DISC FOREIGN KEY(sigla)
             REFERENCES disciplina(sigla), CONSTRAINT FK_ESTEST_ALU FOREIGN KEY(matricula)
             REFERENCES aluno(matricula), CONSTRAINT FK_ESTEST_APRE1 FOREIGN KEY(utilizacao)
             REFERENCES apresentacao(utilizacao), CONSTRAINT FK_ESTEST_APRE2 FOREIGN KEY(selecao)
             REFERENCES apresentacao(selecao), CONSTRAINT FK_ESTEST_APRE3 FOREIGN KEY(organizacao)
             REFERENCES apresentacao(organizacao)) [42102-160]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:648)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:1110)
	at dominio.BD.persistence$criar_tabela_estiloEstudante$fn__96.invoke(persistence.clj:98)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_estiloEstudante.invoke(persistence.clj:97)
	at dominio.dominiox$eval350.invoke(NO_SOURCE_FILE:3)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
org.h2.jdbc.JdbcSQLException: Table "APRESENTACAO" not found; SQL statement:
CREATE TABLE estiloEstudante (matricula VARCHAR(20) NOT NULL, sigla VARCHAR(20) NOT NULL, selecao VARCHAR(20) NOT NULL, organizacao VARCHAR(20) NOT NULL, utilizacao VARCHAR(20) NOT NULL, CONSTRAINT PK_ESTEST PRIMARY KEY(matricula, sigla), CONSTRAINT FK_ESTEST_DISC FOREIGN KEY(sigla)
             REFERENCES disciplina(sigla), CONSTRAINT FK_ESTEST_ALU FOREIGN KEY(matricula)
             REFERENCES aluno(matricula), CONSTRAINT FK_ESTEST_APRE1 FOREIGN KEY(utilizacao)
             REFERENCES apresentacao(utilizacao), CONSTRAINT FK_ESTEST_APRE2 FOREIGN KEY(selecao)
             REFERENCES apresentacao(selecao), CONSTRAINT FK_ESTEST_APRE3 FOREIGN KEY(organizacao)
             REFERENCES apresentacao(organizacao)) [42102-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.schema.Schema.getTableOrView(Schema.java:406)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:175)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:168)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:633)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:1110)
	at dominio.BD.persistence$criar_tabela_estiloEstudante$fn__96.invoke(persistence.clj:98)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_estiloEstudante.invoke(persistence.clj:97)
	at dominio.dominiox$eval350.invoke(NO_SOURCE_FILE:3)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-18 11:39:28 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Value too long for column "NIVEL VARCHAR(20) NOT NULL": "' O nivel pode ser facil, medio ou avancado ' (43)"; SQL statement:
INSERT INTO exercicio (idEx,conteudo,nivel,tipo,xmlExercicio) VALUES (?,?,?,?,?) [22001-160]
11-19 13:05:51 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "EXERCICIO.ID" not found; SQL statement:
SELECT exercicio.id FROM exercicio WHERE exercicio.tipo = 'facil' [42122-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:134)
	at org.h2.command.dml.Select.prepare(Select.java:794)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1119)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:71)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at clojure.java.jdbc.internal$prepare_statement_STAR_.doInvoke(internal.clj:326)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invoke(core.clj:605)
	at clojure.java.jdbc.internal$with_query_results_STAR_.invoke(internal.clj:394)
	at dominio.BD.busca$buscar_exercicio$fn__131.invoke(busca.clj:24)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.busca$buscar_exercicio.invoke(busca.clj:22)
	at dominio.xml.dominiox$eval365.invoke(NO_SOURCE_FILE:4)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-19 15:12:13 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "APRESENTACAO" already exists; SQL statement:
CREATE TABLE apresentacao (idAp VARCHAR(20) NOT NULL, conteudo VARCHAR(50) NOT NULL, tipo VARCHAR(20) NOT NULL, selecao VARCHAR(20) NOT NULL, organizacao VARCHAR(20) NOT NULL, utilizacao VARCHAR(20) NOT NULL, xmlApresentacao CLOB(10000) NOT NULL, CONSTRAINT PK_APRESENTACAO PRIMARY KEY(idAp)) [42101-160]
11-19 15:12:13 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Table "APRESENTACAO" already exists; SQL statement:
CREATE TABLE apresentacao (idAp VARCHAR(20) NOT NULL, conteudo VARCHAR(50) NOT NULL, tipo VARCHAR(20) NOT NULL, selecao VARCHAR(20) NOT NULL, organizacao VARCHAR(20) NOT NULL, utilizacao VARCHAR(20) NOT NULL, xmlApresentacao CLOB(10000) NOT NULL, CONSTRAINT PK_APRESENTACAO PRIMARY KEY(idAp)) [42101-160]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:648)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:713)
	at dominio.BD.persistence$criar_tabela_apresentacao$fn__99.invoke(persistence.clj:120)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_apresentacao.invoke(persistence.clj:119)
	at dominio.xml.dominiox$eval380.invoke(NO_SOURCE_FILE:18)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
org.h2.jdbc.JdbcSQLException: Table "APRESENTACAO" already exists; SQL statement:
CREATE TABLE apresentacao (idAp VARCHAR(20) NOT NULL, conteudo VARCHAR(50) NOT NULL, tipo VARCHAR(20) NOT NULL, selecao VARCHAR(20) NOT NULL, organizacao VARCHAR(20) NOT NULL, utilizacao VARCHAR(20) NOT NULL, xmlApresentacao CLOB(10000) NOT NULL, CONSTRAINT PK_APRESENTACAO PRIMARY KEY(idAp)) [42101-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:108)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:633)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:713)
	at dominio.BD.persistence$criar_tabela_apresentacao$fn__99.invoke(persistence.clj:120)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_apresentacao.invoke(persistence.clj:119)
	at dominio.xml.dominiox$eval380.invoke(NO_SOURCE_FILE:18)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-23 14:19:11 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "CATALOGOBUG" not found; SQL statement:
DELETE FROM catalogoBug WHERE catalogoBug = 'id001' [42122-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:134)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.command.dml.Delete.prepare(Delete.java:125)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1119)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:71)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at clojure.java.jdbc.internal$prepare_statement_STAR_.doInvoke(internal.clj:326)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.java.jdbc.internal$do_prepared_STAR_.doInvoke(internal.clj:357)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clojure.java.jdbc$delete_rows.invoke(jdbc.clj:297)
	at dominio.BD.remocao$remover_catalogoBug$fn__305.invoke(remocao.clj:93)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.remocao$remover_catalogoBug.invoke(remocao.clj:91)
	at dominio.xml.dominiox$eval361.invoke(NO_SOURCE_FILE:2)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-24 12:56:44 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "CONTEUDO" not found; SQL statement:
CREATE TABLE exercicio (idEx VARCHAR(20) NOT NULL, conteudo VARCHAR(50) NOT NULL, nivel VARCHAR(20) NOT NULL, tipo VARCHAR(20) NOT NULL, xmlexercicio CLOB(10000) NOT NULL, CONSTRAINT PK_EXERCICIO PRIMARY KEY(idEx), CONSTRAINT FK_EXERCICIO FOREIGN KEY(conteudo)
             REFERENCES conteudo(conteudo)) [42102-160]
11-24 12:56:44 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Table "CONTEUDO" not found; SQL statement:
CREATE TABLE exercicio (idEx VARCHAR(20) NOT NULL, conteudo VARCHAR(50) NOT NULL, nivel VARCHAR(20) NOT NULL, tipo VARCHAR(20) NOT NULL, xmlexercicio CLOB(10000) NOT NULL, CONSTRAINT PK_EXERCICIO PRIMARY KEY(idEx), CONSTRAINT FK_EXERCICIO FOREIGN KEY(conteudo)
             REFERENCES conteudo(conteudo)) [42102-160]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:648)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:628)
	at dominio.BD.persistence$criar_tabela_exercicio$fn__93.invoke(persistence.clj:84)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_exercicio.invoke(persistence.clj:83)
	at dominio.BD.restore$reload_banco.invoke(restore.clj:27)
	at dominio.xml.dominiox$eval382.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
org.h2.jdbc.JdbcSQLException: Table "CONTEUDO" not found; SQL statement:
CREATE TABLE exercicio (idEx VARCHAR(20) NOT NULL, conteudo VARCHAR(50) NOT NULL, nivel VARCHAR(20) NOT NULL, tipo VARCHAR(20) NOT NULL, xmlexercicio CLOB(10000) NOT NULL, CONSTRAINT PK_EXERCICIO PRIMARY KEY(idEx), CONSTRAINT FK_EXERCICIO FOREIGN KEY(conteudo)
             REFERENCES conteudo(conteudo)) [42102-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.schema.Schema.getTableOrView(Schema.java:406)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:175)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:168)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:633)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:628)
	at dominio.BD.persistence$criar_tabela_exercicio$fn__93.invoke(persistence.clj:84)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_exercicio.invoke(persistence.clj:83)
	at dominio.BD.restore$reload_banco.invoke(restore.clj:27)
	at dominio.xml.dominiox$eval382.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-24 12:57:37 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "EXERCICIO" not found; SQL statement:
DROP TABLE exercicio [42102-160]
11-24 12:57:37 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Table "EXERCICIO" not found; SQL statement:
DROP TABLE exercicio [42102-160]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:648)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$drop_table.invoke(jdbc.clj:243)
	at dominio.BD.persistence$destroi_tabelas$fn__113.invoke(persistence.clj:191)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$destroi_tabelas.invoke(persistence.clj:190)
	at dominio.BD.restore$reload_banco.invoke(restore.clj:20)
	at dominio.xml.dominiox$eval382.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
org.h2.jdbc.JdbcSQLException: Table "EXERCICIO" not found; SQL statement:
DROP TABLE exercicio [42102-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.DropTable.prepareDrop(DropTable.java:69)
	at org.h2.command.ddl.DropTable.update(DropTable.java:112)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:633)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$drop_table.invoke(jdbc.clj:243)
	at dominio.BD.persistence$destroi_tabelas$fn__113.invoke(persistence.clj:191)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$destroi_tabelas.invoke(persistence.clj:190)
	at dominio.BD.restore$reload_banco.invoke(restore.clj:20)
	at dominio.xml.dominiox$eval382.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-24 12:58:09 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "DISCIPLINA" already exists; SQL statement:
CREATE TABLE disciplina (sigla VARCHAR(20) NOT NULL, nome VARCHAR(50) NOT NULL, xmlhierarquia CLOB(10000) NOT NULL, CONSTRAINT PK_DISCIPLINA PRIMARY KEY(sigla)) [42101-160]
11-24 12:58:09 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Table "DISCIPLINA" already exists; SQL statement:
CREATE TABLE disciplina (sigla VARCHAR(20) NOT NULL, nome VARCHAR(50) NOT NULL, xmlhierarquia CLOB(10000) NOT NULL, CONSTRAINT PK_DISCIPLINA PRIMARY KEY(sigla)) [42101-160]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:648)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:486)
	at dominio.BD.persistence$criar_tabela_disciplina$fn__84.invoke(persistence.clj:50)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_disciplina.invoke(persistence.clj:49)
	at dominio.xml.dominiox$eval384.invoke(NO_SOURCE_FILE:2)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
org.h2.jdbc.JdbcSQLException: Table "DISCIPLINA" already exists; SQL statement:
CREATE TABLE disciplina (sigla VARCHAR(20) NOT NULL, nome VARCHAR(50) NOT NULL, xmlhierarquia CLOB(10000) NOT NULL, CONSTRAINT PK_DISCIPLINA PRIMARY KEY(sigla)) [42101-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:108)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:633)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:486)
	at dominio.BD.persistence$criar_tabela_disciplina$fn__84.invoke(persistence.clj:50)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_disciplina.invoke(persistence.clj:49)
	at dominio.xml.dominiox$eval384.invoke(NO_SOURCE_FILE:2)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-24 12:58:10 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ALUNO" already exists; SQL statement:
CREATE TABLE aluno (matricula varchar(20) NOT NULL, nome varchar(50) NOT NULL, sobrenome varchar(100) NOT NULL, curso varchar(50) NOT NULL, email varchar(50), usuario varchar(30) NOT NULL, senha varchar(30) NOT NULL, CONSTRAINT PK_ALUNO PRIMARY KEY(matricula)) [42101-160]
11-24 12:58:10 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Table "ALUNO" already exists; SQL statement:
CREATE TABLE aluno (matricula varchar(20) NOT NULL, nome varchar(50) NOT NULL, sobrenome varchar(100) NOT NULL, curso varchar(50) NOT NULL, email varchar(50), usuario varchar(30) NOT NULL, senha varchar(30) NOT NULL, CONSTRAINT PK_ALUNO PRIMARY KEY(matricula)) [42101-160]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:648)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:713)
	at dominio.BD.persistence$criar_tabela_aluno$fn__81.invoke(persistence.clj:36)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_aluno.invoke(persistence.clj:35)
	at dominio.xml.dominiox$eval388.invoke(NO_SOURCE_FILE:4)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
org.h2.jdbc.JdbcSQLException: Table "ALUNO" already exists; SQL statement:
CREATE TABLE aluno (matricula varchar(20) NOT NULL, nome varchar(50) NOT NULL, sobrenome varchar(100) NOT NULL, curso varchar(50) NOT NULL, email varchar(50), usuario varchar(30) NOT NULL, senha varchar(30) NOT NULL, CONSTRAINT PK_ALUNO PRIMARY KEY(matricula)) [42101-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:108)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:633)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:713)
	at dominio.BD.persistence$criar_tabela_aluno$fn__81.invoke(persistence.clj:36)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_aluno.invoke(persistence.clj:35)
	at dominio.xml.dominiox$eval388.invoke(NO_SOURCE_FILE:4)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-24 13:02:58 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "APRESENTACAO" not found; SQL statement:
DROP TABLE apresentacao [42102-160]
11-24 13:02:58 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Table "APRESENTACAO" not found; SQL statement:
DROP TABLE apresentacao [42102-160]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:648)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$drop_table.invoke(jdbc.clj:243)
	at dominio.BD.persistence$destroi_tabelas$fn__111.invoke(persistence.clj:189)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$destroi_tabelas.invoke(persistence.clj:188)
	at dominio.BD.restore$reload_banco.invoke(restore.clj:20)
	at dominio.xml.dominiox$eval382.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
org.h2.jdbc.JdbcSQLException: Table "APRESENTACAO" not found; SQL statement:
DROP TABLE apresentacao [42102-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.DropTable.prepareDrop(DropTable.java:69)
	at org.h2.command.ddl.DropTable.update(DropTable.java:112)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:633)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$drop_table.invoke(jdbc.clj:243)
	at dominio.BD.persistence$destroi_tabelas$fn__111.invoke(persistence.clj:189)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$destroi_tabelas.invoke(persistence.clj:188)
	at dominio.BD.restore$reload_banco.invoke(restore.clj:20)
	at dominio.xml.dominiox$eval382.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-24 13:03:27 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "DISCIPLINA" already exists; SQL statement:
CREATE TABLE disciplina (sigla VARCHAR(20) NOT NULL, nome VARCHAR(50) NOT NULL, xmlhierarquia CLOB(10000) NOT NULL, CONSTRAINT PK_DISCIPLINA PRIMARY KEY(sigla)) [42101-160]
11-24 13:03:27 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Table "DISCIPLINA" already exists; SQL statement:
CREATE TABLE disciplina (sigla VARCHAR(20) NOT NULL, nome VARCHAR(50) NOT NULL, xmlhierarquia CLOB(10000) NOT NULL, CONSTRAINT PK_DISCIPLINA PRIMARY KEY(sigla)) [42101-160]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:648)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:486)
	at dominio.BD.persistence$criar_tabela_disciplina$fn__84.invoke(persistence.clj:50)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_disciplina.invoke(persistence.clj:49)
	at dominio.xml.dominiox$eval384.invoke(NO_SOURCE_FILE:2)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
org.h2.jdbc.JdbcSQLException: Table "DISCIPLINA" already exists; SQL statement:
CREATE TABLE disciplina (sigla VARCHAR(20) NOT NULL, nome VARCHAR(50) NOT NULL, xmlhierarquia CLOB(10000) NOT NULL, CONSTRAINT PK_DISCIPLINA PRIMARY KEY(sigla)) [42101-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:108)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:633)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:486)
	at dominio.BD.persistence$criar_tabela_disciplina$fn__84.invoke(persistence.clj:50)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_disciplina.invoke(persistence.clj:49)
	at dominio.xml.dominiox$eval384.invoke(NO_SOURCE_FILE:2)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-24 13:03:27 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "CONTEUDO" already exists; SQL statement:
CREATE TABLE conteudo (sigla VARCHAR(20) NOT NULL, conteudo VARCHAR(50) NOT NULL, CONSTRAINT PK_CONTEUDO PRIMARY KEY(sigla, conteudo), CONSTRAINT FK_CONTEUDO FOREIGN KEY(sigla)
    	  REFERENCES disciplina(sigla)) [42101-160]
11-24 13:03:27 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Table "CONTEUDO" already exists; SQL statement:
CREATE TABLE conteudo (sigla VARCHAR(20) NOT NULL, conteudo VARCHAR(50) NOT NULL, CONSTRAINT PK_CONTEUDO PRIMARY KEY(sigla, conteudo), CONSTRAINT FK_CONTEUDO FOREIGN KEY(sigla)
    	  REFERENCES disciplina(sigla)) [42101-160]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:648)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:486)
	at dominio.BD.persistence$criar_tabela_conteudo$fn__87.invoke(persistence.clj:60)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_conteudo.invoke(persistence.clj:59)
	at dominio.xml.dominiox$eval386.invoke(NO_SOURCE_FILE:3)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
org.h2.jdbc.JdbcSQLException: Table "CONTEUDO" already exists; SQL statement:
CREATE TABLE conteudo (sigla VARCHAR(20) NOT NULL, conteudo VARCHAR(50) NOT NULL, CONSTRAINT PK_CONTEUDO PRIMARY KEY(sigla, conteudo), CONSTRAINT FK_CONTEUDO FOREIGN KEY(sigla)
    	  REFERENCES disciplina(sigla)) [42101-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:108)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:633)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:486)
	at dominio.BD.persistence$criar_tabela_conteudo$fn__87.invoke(persistence.clj:60)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_conteudo.invoke(persistence.clj:59)
	at dominio.xml.dominiox$eval386.invoke(NO_SOURCE_FILE:3)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-24 13:03:27 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ALUNO" already exists; SQL statement:
CREATE TABLE aluno (matricula varchar(20) NOT NULL, nome varchar(50) NOT NULL, sobrenome varchar(100) NOT NULL, curso varchar(50) NOT NULL, email varchar(50), usuario varchar(30) NOT NULL, senha varchar(30) NOT NULL, CONSTRAINT PK_ALUNO PRIMARY KEY(matricula)) [42101-160]
11-24 13:03:27 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Table "ALUNO" already exists; SQL statement:
CREATE TABLE aluno (matricula varchar(20) NOT NULL, nome varchar(50) NOT NULL, sobrenome varchar(100) NOT NULL, curso varchar(50) NOT NULL, email varchar(50), usuario varchar(30) NOT NULL, senha varchar(30) NOT NULL, CONSTRAINT PK_ALUNO PRIMARY KEY(matricula)) [42101-160]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:648)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:713)
	at dominio.BD.persistence$criar_tabela_aluno$fn__81.invoke(persistence.clj:36)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_aluno.invoke(persistence.clj:35)
	at dominio.xml.dominiox$eval388.invoke(NO_SOURCE_FILE:4)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
org.h2.jdbc.JdbcSQLException: Table "ALUNO" already exists; SQL statement:
CREATE TABLE aluno (matricula varchar(20) NOT NULL, nome varchar(50) NOT NULL, sobrenome varchar(100) NOT NULL, curso varchar(50) NOT NULL, email varchar(50), usuario varchar(30) NOT NULL, senha varchar(30) NOT NULL, CONSTRAINT PK_ALUNO PRIMARY KEY(matricula)) [42101-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:108)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:633)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:713)
	at dominio.BD.persistence$criar_tabela_aluno$fn__81.invoke(persistence.clj:36)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_aluno.invoke(persistence.clj:35)
	at dominio.xml.dominiox$eval388.invoke(NO_SOURCE_FILE:4)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-24 13:03:29 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "PROFESSOR" already exists; SQL statement:
CREATE TABLE professor (matricula VARCHAR(20) NOT NULL, nome VARCHAR(50) NOT NULL, sobrenome VARCHAR(100) NOT NULL, titulo VARCHAR(20) NOT NULL, email VARCHAR(50) NOT NULL, usuario VARCHAR(30) NOT NULL, senha VARCHAR(30) NOT NULL, CONSTRAINT PK_PROFESSOR PRIMARY KEY(matricula)) [42101-160]
11-24 13:03:29 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Table "PROFESSOR" already exists; SQL statement:
CREATE TABLE professor (matricula VARCHAR(20) NOT NULL, nome VARCHAR(50) NOT NULL, sobrenome VARCHAR(100) NOT NULL, titulo VARCHAR(20) NOT NULL, email VARCHAR(50) NOT NULL, usuario VARCHAR(30) NOT NULL, senha VARCHAR(30) NOT NULL, CONSTRAINT PK_PROFESSOR PRIMARY KEY(matricula)) [42101-160]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:648)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:713)
	at dominio.BD.persistence$criar_tabela_professor$fn__78.invoke(persistence.clj:22)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_professor.invoke(persistence.clj:21)
	at dominio.xml.dominiox$eval394.invoke(NO_SOURCE_FILE:7)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
org.h2.jdbc.JdbcSQLException: Table "PROFESSOR" already exists; SQL statement:
CREATE TABLE professor (matricula VARCHAR(20) NOT NULL, nome VARCHAR(50) NOT NULL, sobrenome VARCHAR(100) NOT NULL, titulo VARCHAR(20) NOT NULL, email VARCHAR(50) NOT NULL, usuario VARCHAR(30) NOT NULL, senha VARCHAR(30) NOT NULL, CONSTRAINT PK_PROFESSOR PRIMARY KEY(matricula)) [42101-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:108)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:633)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:713)
	at dominio.BD.persistence$criar_tabela_professor$fn__78.invoke(persistence.clj:22)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_professor.invoke(persistence.clj:21)
	at dominio.xml.dominiox$eval394.invoke(NO_SOURCE_FILE:7)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-24 13:03:29 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "MINISTRA" already exists; SQL statement:
CREATE TABLE ministra (sigla VARCHAR(20) NOT NULL, matricula VARCHAR(50) NOT NULL, CONSTRAINT PK_MINISTRA PRIMARY KEY(sigla, matricula), CONSTRAINT FK_MIN_DISC FOREIGN KEY(sigla)
             REFERENCES disciplina(sigla), CONSTRAINT FK_MIN_PROF FOREIGN KEY(matricula)
             REFERENCES professor(matricula)) [42101-160]
11-24 13:03:29 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Table "MINISTRA" already exists; SQL statement:
CREATE TABLE ministra (sigla VARCHAR(20) NOT NULL, matricula VARCHAR(50) NOT NULL, CONSTRAINT PK_MINISTRA PRIMARY KEY(sigla, matricula), CONSTRAINT FK_MIN_DISC FOREIGN KEY(sigla)
             REFERENCES disciplina(sigla), CONSTRAINT FK_MIN_PROF FOREIGN KEY(matricula)
             REFERENCES professor(matricula)) [42101-160]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:648)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:516)
	at dominio.BD.persistence$criar_tabela_ministra$fn__90.invoke(persistence.clj:71)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_ministra.invoke(persistence.clj:70)
	at dominio.xml.dominiox$eval396.invoke(NO_SOURCE_FILE:8)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
org.h2.jdbc.JdbcSQLException: Table "MINISTRA" already exists; SQL statement:
CREATE TABLE ministra (sigla VARCHAR(20) NOT NULL, matricula VARCHAR(50) NOT NULL, CONSTRAINT PK_MINISTRA PRIMARY KEY(sigla, matricula), CONSTRAINT FK_MIN_DISC FOREIGN KEY(sigla)
             REFERENCES disciplina(sigla), CONSTRAINT FK_MIN_PROF FOREIGN KEY(matricula)
             REFERENCES professor(matricula)) [42101-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:108)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:633)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:516)
	at dominio.BD.persistence$criar_tabela_ministra$fn__90.invoke(persistence.clj:71)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_ministra.invoke(persistence.clj:70)
	at dominio.xml.dominiox$eval396.invoke(NO_SOURCE_FILE:8)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-24 13:03:30 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "CONTEUDOALUNO" already exists; SQL statement:
CREATE TABLE conteudoAluno (matricula varchar(20) NOT NULL, conteudo varchar(50) NOT NULL, bom float NOT NULL, medio float NOT NULL, ruim float NOT NULL, CONSTRAINT PK_CONTEUDO_ALUNO PRIMARY KEY(matricula, conteudo), CONSTRAINT FK_CONTAL_AL 
  	    FOREIGN KEY (matricula) REFERENCES aluno(matricula), CONSTRAINT FK_CONTAL_CONT 
  	    FOREIGN KEY(conteudo) REFERENCES conteudo(conteudo)) [42101-160]
11-24 13:03:30 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Table "CONTEUDOALUNO" already exists; SQL statement:
CREATE TABLE conteudoAluno (matricula varchar(20) NOT NULL, conteudo varchar(50) NOT NULL, bom float NOT NULL, medio float NOT NULL, ruim float NOT NULL, CONSTRAINT PK_CONTEUDO_ALUNO PRIMARY KEY(matricula, conteudo), CONSTRAINT FK_CONTAL_AL 
  	    FOREIGN KEY (matricula) REFERENCES aluno(matricula), CONSTRAINT FK_CONTAL_CONT 
  	    FOREIGN KEY(conteudo) REFERENCES conteudo(conteudo)) [42101-160]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:648)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:713)
	at dominio.BD.persistence$criar_tabela_conteudoAluno$fn__102.invoke(persistence.clj:135)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_conteudoAluno.invoke(persistence.clj:134)
	at dominio.xml.dominiox$eval398.invoke(NO_SOURCE_FILE:9)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
org.h2.jdbc.JdbcSQLException: Table "CONTEUDOALUNO" already exists; SQL statement:
CREATE TABLE conteudoAluno (matricula varchar(20) NOT NULL, conteudo varchar(50) NOT NULL, bom float NOT NULL, medio float NOT NULL, ruim float NOT NULL, CONSTRAINT PK_CONTEUDO_ALUNO PRIMARY KEY(matricula, conteudo), CONSTRAINT FK_CONTAL_AL 
  	    FOREIGN KEY (matricula) REFERENCES aluno(matricula), CONSTRAINT FK_CONTAL_CONT 
  	    FOREIGN KEY(conteudo) REFERENCES conteudo(conteudo)) [42101-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:108)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:633)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:713)
	at dominio.BD.persistence$criar_tabela_conteudoAluno$fn__102.invoke(persistence.clj:135)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_conteudoAluno.invoke(persistence.clj:134)
	at dominio.xml.dominiox$eval398.invoke(NO_SOURCE_FILE:9)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-24 13:03:30 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "EXERCICIOALUNO" already exists; SQL statement:
CREATE TABLE exercicioAluno (matricula varchar(20) NOT NULL, conteudo varchar(50) NOT NULL, idEx varchar(20) NOT NULL, bom float NOT NULL, medio float NOT NULL, ruim float NOT NULL, CONSTRAINT PK_EXALUNO PRIMARY KEY(matricula, conteudo, idEx), CONSTRAINT FK_EXALUNO_A 
  	    FOREIGN KEY (matricula) REFERENCES aluno(matricula), CONSTRAINT FK_EXALUNO_C 
  	    FOREIGN KEY (conteudo) REFERENCES conteudo(conteudo), CONSTRAINT FK_EXALUNO_EX 
  	    FOREIGN KEY (idEx) REFERENCES  exercicio(idEx)) [42101-160]
11-24 13:03:30 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Table "EXERCICIOALUNO" already exists; SQL statement:
CREATE TABLE exercicioAluno (matricula varchar(20) NOT NULL, conteudo varchar(50) NOT NULL, idEx varchar(20) NOT NULL, bom float NOT NULL, medio float NOT NULL, ruim float NOT NULL, CONSTRAINT PK_EXALUNO PRIMARY KEY(matricula, conteudo, idEx), CONSTRAINT FK_EXALUNO_A 
  	    FOREIGN KEY (matricula) REFERENCES aluno(matricula), CONSTRAINT FK_EXALUNO_C 
  	    FOREIGN KEY (conteudo) REFERENCES conteudo(conteudo), CONSTRAINT FK_EXALUNO_EX 
  	    FOREIGN KEY (idEx) REFERENCES  exercicio(idEx)) [42101-160]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:648)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:943)
	at dominio.BD.persistence$criar_tabela_exercicioAluno$fn__105.invoke(persistence.clj:151)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_exercicioAluno.invoke(persistence.clj:150)
	at dominio.xml.dominiox$eval400.invoke(NO_SOURCE_FILE:10)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
org.h2.jdbc.JdbcSQLException: Table "EXERCICIOALUNO" already exists; SQL statement:
CREATE TABLE exercicioAluno (matricula varchar(20) NOT NULL, conteudo varchar(50) NOT NULL, idEx varchar(20) NOT NULL, bom float NOT NULL, medio float NOT NULL, ruim float NOT NULL, CONSTRAINT PK_EXALUNO PRIMARY KEY(matricula, conteudo, idEx), CONSTRAINT FK_EXALUNO_A 
  	    FOREIGN KEY (matricula) REFERENCES aluno(matricula), CONSTRAINT FK_EXALUNO_C 
  	    FOREIGN KEY (conteudo) REFERENCES conteudo(conteudo), CONSTRAINT FK_EXALUNO_EX 
  	    FOREIGN KEY (idEx) REFERENCES  exercicio(idEx)) [42101-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:108)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:633)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:943)
	at dominio.BD.persistence$criar_tabela_exercicioAluno$fn__105.invoke(persistence.clj:151)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_exercicioAluno.invoke(persistence.clj:150)
	at dominio.xml.dominiox$eval400.invoke(NO_SOURCE_FILE:10)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-24 13:03:31 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ESTILOESTUDANTE" already exists; SQL statement:
CREATE TABLE estiloEstudante (matricula VARCHAR(20) NOT NULL, sigla VARCHAR(20) NOT NULL, selecao VARCHAR(20) NOT NULL, organizacao VARCHAR(20) NOT NULL, utilizacao VARCHAR(20) NOT NULL, CONSTRAINT PK_ESTEST PRIMARY KEY(matricula, sigla), CONSTRAINT FK_ESTEST_DISC FOREIGN KEY(sigla)
             REFERENCES disciplina(sigla), CONSTRAINT FK_ESTEST_ALU FOREIGN KEY(matricula)
             REFERENCES aluno(matricula), CONSTRAINT FK_ESTEST_APRE1 FOREIGN KEY(utilizacao)
             REFERENCES apresentacao(utilizacao), CONSTRAINT FK_ESTEST_APRE2 FOREIGN KEY(selecao)
             REFERENCES apresentacao(selecao), CONSTRAINT FK_ESTEST_APRE3 FOREIGN KEY(organizacao)
             REFERENCES apresentacao(organizacao)) [42101-160]
11-24 13:03:31 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Table "ESTILOESTUDANTE" already exists; SQL statement:
CREATE TABLE estiloEstudante (matricula VARCHAR(20) NOT NULL, sigla VARCHAR(20) NOT NULL, selecao VARCHAR(20) NOT NULL, organizacao VARCHAR(20) NOT NULL, utilizacao VARCHAR(20) NOT NULL, CONSTRAINT PK_ESTEST PRIMARY KEY(matricula, sigla), CONSTRAINT FK_ESTEST_DISC FOREIGN KEY(sigla)
             REFERENCES disciplina(sigla), CONSTRAINT FK_ESTEST_ALU FOREIGN KEY(matricula)
             REFERENCES aluno(matricula), CONSTRAINT FK_ESTEST_APRE1 FOREIGN KEY(utilizacao)
             REFERENCES apresentacao(utilizacao), CONSTRAINT FK_ESTEST_APRE2 FOREIGN KEY(selecao)
             REFERENCES apresentacao(selecao), CONSTRAINT FK_ESTEST_APRE3 FOREIGN KEY(organizacao)
             REFERENCES apresentacao(organizacao)) [42101-160]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:648)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:1110)
	at dominio.BD.persistence$criar_tabela_estiloEstudante$fn__96.invoke(persistence.clj:98)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_estiloEstudante.invoke(persistence.clj:97)
	at dominio.xml.dominiox$eval402.invoke(NO_SOURCE_FILE:11)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
org.h2.jdbc.JdbcSQLException: Table "ESTILOESTUDANTE" already exists; SQL statement:
CREATE TABLE estiloEstudante (matricula VARCHAR(20) NOT NULL, sigla VARCHAR(20) NOT NULL, selecao VARCHAR(20) NOT NULL, organizacao VARCHAR(20) NOT NULL, utilizacao VARCHAR(20) NOT NULL, CONSTRAINT PK_ESTEST PRIMARY KEY(matricula, sigla), CONSTRAINT FK_ESTEST_DISC FOREIGN KEY(sigla)
             REFERENCES disciplina(sigla), CONSTRAINT FK_ESTEST_ALU FOREIGN KEY(matricula)
             REFERENCES aluno(matricula), CONSTRAINT FK_ESTEST_APRE1 FOREIGN KEY(utilizacao)
             REFERENCES apresentacao(utilizacao), CONSTRAINT FK_ESTEST_APRE2 FOREIGN KEY(selecao)
             REFERENCES apresentacao(selecao), CONSTRAINT FK_ESTEST_APRE3 FOREIGN KEY(organizacao)
             REFERENCES apresentacao(organizacao)) [42101-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:108)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:633)
	at clojure.java.jdbc$do_commands$fn__197.invoke(jdbc.clj:188)
	at clojure.java.jdbc.internal$transaction_STAR_.invoke(internal.clj:206)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:1110)
	at dominio.BD.persistence$criar_tabela_estiloEstudante$fn__96.invoke(persistence.clj:98)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.persistence$criar_tabela_estiloEstudante.invoke(persistence.clj:97)
	at dominio.xml.dominiox$eval402.invoke(NO_SOURCE_FILE:11)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
11-24 13:28:24 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "APRESENTACAO.ID" not found; SQL statement:
SELECT apresentacao.id FROM apresentacao WHERE apresentacao.id = 'v002' [42122-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:134)
	at org.h2.command.dml.Select.prepare(Select.java:794)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1119)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:71)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at clojure.java.jdbc.internal$prepare_statement_STAR_.doInvoke(internal.clj:326)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invoke(core.clj:605)
	at clojure.java.jdbc.internal$with_query_results_STAR_.invoke(internal.clj:394)
	at dominio.BD.busca$buscar_apresentacao$fn__158.invoke(busca.clj:39)
	at clojure.java.jdbc.internal$with_connection_STAR_.invoke(internal.clj:188)
	at dominio.BD.busca$buscar_apresentacao.invoke(busca.clj:37)
	at dominio.xml.dominiox$eval396.invoke(NO_SOURCE_FILE:8)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6477)
	at clojure.core$eval.invoke(core.clj:2797)
	at clojure.main$repl$read_eval_print__6405.invoke(main.clj:245)
	at clojure.main$repl$fn__6410.invoke(main.clj:266)
	at clojure.main$repl.doInvoke(main.clj:266)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at user$eval27$acc__3088__auto____30$fn__32.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.lang.Thread.run(Thread.java:679)
02-21 16:42:05 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ALUNOS" not found; SQL statement:
SELECT * FROM ALUNOS [42102-160]
02-23 17:42:28 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ALUNOS" not found; SQL statement:
SELECT * FROM ALUNOS [42102-160]
